# This workflow will install Python dependencies and run tests with a single version of Python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
        
    - name: Run tests
      run: |
        pip install pytest
        pytest --verbose
        
    - name: Lint with flake8
      run: |
        pip install flake8
        
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Lint with pylint
      run: |
        # pip install pylint
        # pylint ./todo --recursive=true
        
    - name: Lint with mypy
      run: |
        pip install mypy
        mypy .        
